/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include <stdio.h>
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxSrc_reg.h"
#include "IfxStm_reg.h"
#include "IfxGPt12_reg.h"
#include "IfxAsclin_reg.h"
#include "IfxScu_reg.h"
#include "stdint.h"
#include "task.h"
#include "cbuff.h"
IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;
///////////////////////////////////////////////////////////////////////////////
// Defines
///////////////////////////////////////////////////////////////////////////////
#define TEST_BLINK_LEDS            0
#define TEST_GPIO_OUT_IN           1
#define SW_INTERRUPT_PRIORITY      0
#define TIMER_0_INTERRUPT_PRIORITY 255
#define GPT1_INTERRUPT_PRIORITY    0
///////////////////////////////////////////////////////////////////////////////
// If CLK == 100Mhz:
//      10ms = 0.010, CLK = 100Mhz (ie bit-0 toogles at 0.000,000,01s, 10ns)
//      To get 10ms we need 0.01 / 0.00000001 ticks = 1000000 ticks
//      2^x = 1000000 -> xlog(2) = log(1000000) -> x = 6 / log(2) ->
//          x = 6 / 0.301 = 19.9 = 20
//      Therefore x = 20, so 2^20 is approximately 10ms toggle, so every 10ms the
//      LED should toggle
///////////////////////////////////////////////////////////////////////////////
#define COMPARE_BIT 0
#if (COMPARE_BIT == 1)
  #define BIT_NUM  16
  #define BIT_SZ   0
#else
  #define BIT_NUM  0
  #define BIT_SZ   31
  #define TIME_ADD 125000 /* Add this to comparator should provide a 5ms interrupt */
#endif
///////////////////////////////////////////////////////////////////////////////
// Constants
///////////////////////////////////////////////////////////////////////////////
const unsigned int DELAY = 1000000;
///////////////////////////////////////////////////////////////////////////////
// Modules
///////////////////////////////////////////////////////////////////////////////
volatile Ifx_P      *p_pin20   = (volatile Ifx_P      *)0xF003B400u; // IfxPort_reg.h  - LED
volatile Ifx_P      *p_pin33   = (volatile Ifx_P      *)0xF003C100u; // IfxPort_reg.h  - LED
volatile Ifx_P      *p_pin14   = (volatile Ifx_P      *)0xF003AE00u; // IfxPort_reg.h  - UART 0 - RX, 1 - TX
volatile Ifx_P      *p_pin15   = (volatile Ifx_P      *)0xF003AF00u; // IfxPort_reg.h  - UART 0 - RX, 1 - TX
volatile Ifx_SRC    *p_src     = (volatile Ifx_SRC    *)0xF0038000u; // IfxSrc_reg.h   - Service Request Controller
volatile Ifx_STM    *p_stm0    = (volatile Ifx_STM    *)0xF0001000u; // IfxStm_reg.h   - Timer using p-src
volatile Ifx_GPT12  *p_gpt12   = (volatile Ifx_GPT12  *)0xF0001800u; // IfxGPt12_reg.h - General purpose timer
volatile Ifx_ASCLIN *p_asclin0 = (volatile Ifx_ASCLIN *)0xF0000600u; // IfxAsclin_reg.h - Async/Sync interface - UART, SPI, I2C, LIN
volatile Ifx_SCU    *p_scu     = (volatile Ifx_SCU    *)0xF0036000u;
///////////////////////////////////////////////////////////////////////////////
// Globals
///////////////////////////////////////////////////////////////////////////////
const    uint16_t TOGGLE_VALUE      = 0xfffe;
volatile uint32_t timer_0_isr_count = 0;
volatile uint32_t gpt1_isr_count    = 0;
volatile uint32_t toggle            = 0;
volatile uint32_t int_toggle_p6     = 0;
volatile uint32_t int_toggle_p7     = 0;
volatile uint64_t compare_value     = (uint64_t)0;
#define MAX_DATA 100
volatile int32_t  data[MAX_DATA]    = {0,};
volatile struct cbuff_t buffer      = {{0}};
///////////////////////////////////////////////////////////////////////////////
// Delay
///////////////////////////////////////////////////////////////////////////////
void delay(int d) {
    volatile int i = 0;
    for (i = 0; i < d; i++) {
        i++;
    }
}
///////////////////////////////////////////////////////////////////////////////
// GPT1 Timer Interrupt Handler
///////////////////////////////////////////////////////////////////////////////
void gpt1_isr_exec() {
    p_pin33->OUT.B.P7     = ~p_pin33->OUT.B.P7;
    p_gpt12->T3CON.B.T3R  = 0;            // Timer run, timer run bit, 1 - timer run, 0 - timer stop
    p_gpt12->T3.B.T3      = TOGGLE_VALUE; // Put some value into the timer
    p_gpt12->T3CON.B.T3R  = 1;            // Timer run, timer run bit, 1 - timer run, 0 - timer stop
    IfxCpu_enableInterrupts();
    gpt1_isr_count++;
    if (gpt1_isr_count >= 10) {
        gpt1_isr_count = 0;
    }
}

IFX_INTERRUPT (gpt1_isr, 0, GPT1_INTERRUPT_PRIORITY) {
    gpt1_isr_exec();
}
// ----------------------------------------------------------------------------
///////////////////////////////////////////////////////////////////////////////
// Timer-0 Interrupt Handler
// ----------------------------------------------------------------------------
///////////////////////////////////////////////////////////////////////////////
struct exec_t {
    int data;
};

static struct exec_t exec_data = {{0}};
void timer_0_isr_exec(void) {
    IfxCpu_disableInterrupts();
    //p_pin33->OUT.B.P6 = ~p_pin33->OUT.B.P6;
    p_stm0->ISCR.B.CMP0IRR  = 1;
#if (COMPARE_BIT == 1)
    p_stm0->CMP[0].B.CMPVAL = (p_stm0->CMP[0].B.CMPVAL == (uint32_t)((uint32_t)0x1 << (BIT_NUM)))
            ? (uint32_t)0 : (uint32_t)((uint32_t)0x1 << (BIT_NUM));
#else
    p_stm0->CMP[0].B.CMPVAL += TIME_ADD;
#endif
    p_stm0->ISCR.B.CMP0IRR  = 0;
    task_exec((void *)&exec_data);
    IfxCpu_enableInterrupts();
}

IFX_INTERRUPT (timer_0_isr, 0, TIMER_0_INTERRUPT_PRIORITY) {
    timer_0_isr_exec();
}
///////////////////////////////////////////////////////////////////////////////
// SW Interrupt Handler
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
// Tasks - Foreground task
///////////////////////////////////////////////////////////////////////////////
void task_5ms() {
    static int32_t i = 22;
    p_pin20->OUT.B.P11 = ~p_pin20->OUT.B.P11;
    cbuff_put((struct cbuff_t *)&buffer, i);
    i++;
}

void task_10ms() {
    p_pin20->OUT.B.P12 = ~p_pin20->OUT.B.P12;
}

void task_20ms() {
    static int32_t j = 0;
    p_pin20->OUT.B.P13 = ~p_pin20->OUT.B.P13;
    cbuff_get((struct cbuff_t *)&buffer, &j);
}

void task_40ms() {
    p_pin20->OUT.B.P14 = ~p_pin20->OUT.B.P14;
    //p_asclin0->TXFIFOCON.B.FLUSH = 0x00; // Flush it
    p_asclin0->TXDATA.B.DATA = 0x000000AA;
    //p_asclin0->TXFIFOCON.B.FLUSH = 0x01; // Flush it
    //p_pin14->OUT.B.P0 = p_pin20->OUT.B.P14;
    //p_pin14->OUT.B.P1 = p_pin20->OUT.B.P14;
}
///////////////////////////////////////////////////////////////////////////
// Main - Background task
///////////////////////////////////////////////////////////////////////////
void core0_main(void) {
    IfxCpu_enableInterrupts();
    ///////////////////////////////////////////////////////////////////////////
    // !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
    // Enable the watchdogs and service them periodically if it is required
    ///////////////////////////////////////////////////////////////////////////
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    ///////////////////////////////////////////////////////////////////////////
    // Wait for CPU sync event
    ///////////////////////////////////////////////////////////////////////////
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    ///////////////////////////////////////////////////////////////////////////
    // Tasks
    ///////////////////////////////////////////////////////////////////////////
    cbuff_init((struct cbuff_t *)&buffer, (int32_t *)data, MAX_DATA);
    task_init();
    task_add(task_5ms,  4,  0); // Approx. 5ms
    task_add(task_10ms, 8,  0); // Approx. 10ms
    task_add(task_20ms, 16, 0); // Approx. 20ms
    task_add(task_40ms, 32, 0); // Approx. 40ms
    ///////////////////////////////////////////////////////////////////////////
    // SERVICE REQUEST SET UP
    ///////////////////////////////////////////////////////////////////////////
    // GPT1 Service Request Setup, timer-3 is SR1, see Figure 216
    ///////////////////////////////////////////////////////////////////////////
    p_src->GPT12.GPT12[0].T3.B.SRPN = GPT1_INTERRUPT_PRIORITY;   // Set priority
    p_src->GPT12.GPT12[0].T3.B.SRE  = 1;                         // Enable service request
    p_src->GPT12.GPT12[0].T3.B.TOS  = 0;                         // CPU0 is the service provider
    ///////////////////////////////////////////////////////////////////////////
    // STM0 Service Request Setup
    ///////////////////////////////////////////////////////////////////////////
    p_src->STM.STM[0].SR[0].B.SRPN = TIMER_0_INTERRUPT_PRIORITY; // Set priority so the above handler will service it
    p_src->STM.STM[0].SR[0].B.SRE  = 1;                          // Enable service request
    p_src->STM.STM[0].SR[0].B.TOS  = 0;                          // CPU0 is the service provider
    ///////////////////////////////////////////////////////////////////////////
    // MODULE SET UP
    ///////////////////////////////////////////////////////////////////////////
    // GPT12 SET UP (General Purpose Timer/Counter)
    ///////////////////////////////////////////////////////////////////////////
    p_gpt12->CLC.B.DISR    = 0;            // Enable the clock module
    p_gpt12->CLC.B.EDIS    = 1;            // Disable sleep mode request
    p_gpt12->ACCEN0.U      = 0xffffffffu;  // Enable everything
    p_gpt12->T3.B.T3       = TOGGLE_VALUE; // Put some value into the timer
    p_gpt12->T3CON.B.T3I   = 0x2;          // Timer mode, input parameter selection
    p_gpt12->T3CON.B.BPS1  = 3;            // f/64
    p_gpt12->T3CON.B.T3M   = 0;            // Timer mode, timer mode control
    p_gpt12->T3CON.B.T3UD  = 1;            // Count down, count direction, should underflow and produce interrupt
    p_gpt12->T3CON.B.T3UDE = 0;           // External up/down disabled
    p_gpt12->T3CON.B.T3OE  = 0;            // alternate function disabled
    p_gpt12->T3CON.B.T3R   = 1;            // Timer run, timer run bit, 1 - timer run, 0 - timer stop
    ///////////////////////////////////////////////////////////////////////////
    // STM0 Set Up (System Timer)
    ///////////////////////////////////////////////////////////////////////////
#if (COMPARE_BIT == 1)
    p_stm0->CMP[0].B.CMPVAL = (uint32_t)((uint32_t)0x1 << (BIT_NUM));
    p_stm0->CMP[1].B.CMPVAL = (uint32_t)0;
#else
    p_stm0->CMP[0].B.CMPVAL = p_stm0->TIM0.B.STM_31_0 + TIME_ADD;
    p_stm0->CMP[1].B.CMPVAL = (uint32_t)0;
#endif
    p_stm0->CMCON.B.MSIZE0  = BIT_SZ;  // 32 bit count value CMP[0]
    p_stm0->CMCON.B.MSTART0 = BIT_NUM; // CMP0 register start-bit
    p_stm0->CMCON.B.MSIZE1  = BIT_SZ;  // 32 bit count value
    p_stm0->CMCON.B.MSTART1 = BIT_SZ;  // CMP1 register start bit
    p_stm0->ICR.B.CMP0EN    = 1;       // Enable CMP0
    p_stm0->ICR.B.CMP0OS    = 0;       // Sel STMIR0 as interrupt
    p_stm0->ICR.B.CMP1EN    = 0;       // Enable CMP1
    p_stm0->ICR.B.CMP1OS    = 0;       // Sel STMIR1 if enabled
    ///////////////////////////////////////////////////////////////////////////
    // ASC (Async/Sync or UART Set Up
    ///////////////////////////////////////////////////////////////////////////
    /*
     * (1)   SCU_vResetENDINIT (0); // enable ENDINIT register
     * (2)   ASCLIN0_CLC = 0x000; // disable module control
     * (3)   dummy = ASCLIN0_CLC; //read back
     * (4)   SCU_vSetENDINIT (0); // lock ENDINIT register
     * (5)   ASCLIN0_CSR = 0; // clk source, no clk
     * (6)   ASCLIN0_IOCR = 0x10000001; // Loopback
     * (7)   ASCLIN0_TXFIFOCON = 0x00000043; // init TXFIFO
     * (8)   ASCLIN0_RXFIFOCON = 0x00000043; // init RXFIFO
     * (9)   ASCLIN0_BITCON = 0x830F0009; // OS 16, SP 7,8,9, PS 10
     * (10)  ASCLIN0_FRAMECON = 0x40000200; // 1 Stop, Init Mode, P
     * (11)  ASCLIN0_DATCON = 0x7; //8 Data Bits
     * (12)  ASCLIN0_BRG = 0x00300C35; //divider for Baudrate
     * (13)  ASCLIN0_FLAGSCLEAR = 0xFFFFFFFFF;// Clear all Flags
     * (14)  ASCLIN0_FLAGSENABLE = 0xF0000000; // Enable TX/RX Int.
     * (15)  SRC_ASCLIN0TX = (1 << 10) | ASC0TX_PRIO;
     * (16)  SRC_ASCLIN0RX = (1 << 10) | ASC0RX_PRIO;
     * (17)  interruptHandlerInstall (ASC0TX_PRIO, & ASC0_TX_irq);
     * (18)  interruptHandlerInstall (ASC0RX_PRIO, & ASC0_RX_irq);
     * (19)  ASCLIN0_FRAMECON |= 0x00010000;// Mode ASC
     *
     *
     * */
    // (1) SCU_vResetENDINIT(0); // enable ENDINIT register
    p_scu->EICON0.B.ENDINIT = 0;
    // (2) Enable module control
    p_asclin0->CLC.B.DISR   = 0x0; // Enable the module
    // (3) dummy = ASCLIN0_CLC; //read back
    uint32_t dummy = p_asclin0->CLC.U;
    (void)dummy;
    // (4) SCU_vSetENDINIT (0); // lock ENDINIT register
    p_scu->EICON0.B.ENDINIT = 1;
    // (5) No clk
    p_asclin0->CSR.B.CLKSEL = 0x0;
    // (6)
    p_asclin0->IOCR.U = 0x10000001;
    // (7) Init TxFIFO (8) Init RxFIFO
    p_asclin0->TXFIFOCON.U = 0x00000043;
    p_asclin0->RXFIFOCON.U = 0x00000043;
    // (9)
    p_asclin0->BITCON.U = 0x830F0009;
    // (10)
    p_asclin0->FRAMECON.U = 0x40000200;
    // (11)
    p_asclin0->DATCON.U = 0x7;
    // (12)
    p_asclin0->BRG.U = 0x01752FFF; // 0x01752FFF - 115200KBaud, 0x00300C35 - 19.2KBaud
    p_asclin0->FLAGSCLEAR.U = 0xFFFFFFFF;
    p_asclin0->FLAGSENABLE.U = 0x00000000;
    // (19)
    p_asclin0->FRAMECON.U |= 0x00010000;
    p_asclin0->CSR.B.CLKSEL = 0x2;
// //    // Initialize follows this sequence (see
// //    p_asclin0->CSR.B.CLKSEL = 0;
// //    while (p_asclin0->CSR.B.CON == 1);
// //    //delay(1000);
// //    p_asclin0->FRAMECON.B.MODE   = 0x00; // INIT mode
// //    p_asclin0->CSR.B.CLKSEL = 2;
// //    while (p_asclin0->CSR.B.CON == 0);
// //    //delay(1000);
// //    p_asclin0->CSR.B.CLKSEL = 0;
// //    while (p_asclin0->CSR.B.CON == 1);
// //    //delay(1000);
// //    p_asclin0->FRAMECON.B.MODE   = 0x01; // ASC mode
// //    p_asclin0->CSR.B.CLKSEL = 2;
// //    while (p_asclin0->CSR.B.CON == 0);
// //    //delay(1000);
//
//     p_asclin0->FRAMECON.B.MODE = 0x01; // ASC mode
//     p_asclin0->FRAMECON.B.IDLE = 0x00; // Idle time between TXFIFO data
//     p_asclin0->FRAMECON.B.STOP = 0x01; // 1 Stop bit
//     p_asclin0->FRAMECON.B.LEAD = 0x00; // Lead time (for SPI mode)
//     p_asclin0->FRAMECON.B.MSB  = 0x00; // lsb first
//     p_asclin0->FRAMECON.B.CEN  = 0x00; // Collision detection
//     p_asclin0->FRAMECON.B.PEN  = 0x00; // Parity disabled
//     p_asclin0->FRAMECON.B.ODD  = 0x00; // Odd if enabled, in this case disabled so don't-care
//     p_asclin0->IOCR.B.ALTI  = 0x00; // Alternate input selection
//     p_asclin0->IOCR.B.DEPTH = 0x05; // Digital glitch filter
//     p_asclin0->IOCR.B.CTS   = 0x00; // CTS ACTSA select, this needs to be shutdown
//     p_asclin0->IOCR.B.RCPOL = 0x00; // RTS CTS Polarity, active high
//     p_asclin0->IOCR.B.CPOL  = 0x00; // Clock Polarity, idle low
//     p_asclin0->IOCR.B.SPOL  = 0x00; // Slave Polarity Sync Mode
//     p_asclin0->IOCR.B.LB    = 0x00; // Loop-Back Mode, disabled
//     p_asclin0->IOCR.B.CTSEN = 0x00; // Input Signal CTS Enable, disabled
//     // p_asclin0->IOCR.B.RXM = read-only
//     // p_asclin0->IOCR.B.TXM = read-only
//     p_asclin0->DATCON.B.DATLEN   = 0x07; // 8 Bit data
//     p_asclin0->DATCON.B.HO       = 0x00; // Header Only, LIN stuff, Header and response expected
//     p_asclin0->DATCON.B.RM       = 0x00; // Response Mode, LIN stuff
//     p_asclin0->DATCON.B.CSM      = 0x00; // Classic CRC
//     p_asclin0->DATCON.B.RESPONSE = 0x00; // Response timeout threshold limit
//
//     //p_asclin0->BRG.B.NUMERATOR   = 1;  // Baud Rate Generator
//     //p_asclin0->BRG.B.DENOMINATOR = 1;    // Baud Rate Generator
//
//     p_asclin0->BRG.U = 0x00300C35;
//
//
//     //p_asclin0->BITCON.B.PRESCALER    = 5; // See Digital Glitch Filter above
//     //p_asclin0->BITCON.B.OVERSAMPLING = 15; // Oversampling factor
//     //p_asclin0->BITCON.B.SAMPLEPOINT  = 0x07; // Sample point at 7
//     //p_asclin0->BITCON.B.SM = 0x01; // Samples per bit 1 - 3 samples/bit
//     p_asclin0->BITCON.U = 0x830F0009;
//     p_asclin0->RXFIFOCON.U = 0x00000043; // Don't use the RX FIFO
//     p_asclin0->TXFIFOCON.U = 0x00000043; // 0x00000043 is same as below
// //    p_asclin0->TXFIFOCON.B.ENO   = 1; // TXFIFO Outlet Enable
// //    p_asclin0->TXFIFOCON.B.FLUSH = 0; // Flush FIFO immediately
// //    p_asclin0->TXFIFOCON.B.INW   = 1; // 8-bit
// //    p_asclin0->TXFIFOCON.B.FM = 0; // FIFO mode, 1 - single move mode
// //    p_asclin0->TXFIFOCON.B.INTLEVEL = 0; // Make interrupt level 5 so interrupt will be triggered here, for now don't do interrupts
    ///////////////////////////////////////////////////////////////////////////
    // GPIO Set Up
    ///////////////////////////////////////////////////////////////////////////
    // BLUE LEDS - PORT 20, PINS 11 to 14
    ///////////////////////////////////////////////////////////////////////////
    p_pin20->PDISC.U       = 0x00;    // Set the input as digital input via the schmidtt trigger
    p_pin20->IOCR8.B.PC11  = 0x10; // Digital output, not alt-func, LED should turn on immediately
    p_pin20->IOCR12.B.PC12 = 0x10;
    p_pin20->IOCR12.B.PC13 = 0x10;
    p_pin20->IOCR12.B.PC14 = 0x10;
    p_pin20->OUT.B.P11     = 1;    // LED should turn off
    p_pin20->OUT.B.P12     = 1;
    p_pin20->OUT.B.P13     = 1;
    p_pin20->OUT.B.P14     = 1;
    ///////////////////////////////////////////////////////////////////////////
    // GREEN LEDS - PORT 33, PINS 4 to 7
    ///////////////////////////////////////////////////////////////////////////
    p_pin33->PDISC.U     = 0x00; // Digital function, not analog
    p_pin33->IOCR4.B.PC4 = 0x10; // Digital output, not alt-func, LED should turn on immediately
    p_pin33->IOCR4.B.PC5 = 0x10;
    p_pin33->IOCR4.B.PC6 = 0x10;
    p_pin33->IOCR4.B.PC7 = 0x10;
    p_pin33->OUT.B.P4    = 1;    // LED should turn off
    p_pin33->OUT.B.P5    = 1;
    p_pin33->OUT.B.P6    = 1;
    p_pin33->OUT.B.P7    = 1;
    ///////////////////////////////////////////////////////////////////////////
    // UART - PORT 14, PINS 0 (RX) and 1 (TX)
    ///////////////////////////////////////////////////////////////////////////
    p_pin14->PDISC.U     = 0x00; // Digital function, not analog
    p_pin14->IOCR0.B.PC0 = 0x00; // UART RX, pin 0, disc-in
    p_pin14->IOCR0.B.PC1 = 0x12; // UART TX, pin 1, alt-func (see table 2.8, Infineon-TC38x-DataSheet-v01_02-EN.pdf)
    p_pin14->PDR0.B.PD0  = 0x00; // Strong driver, sharp edge
    p_pin14->PDR0.B.PD1  = 0x00; // Strong driver, sharp edge
    p_pin14->PDR0.B.PL0  = 0x02; // 3.3v
    p_pin14->PDR0.B.PL1  = 0x02; // 3.3v
    //p_pin14->IOCR0.B.PC0 = 0x10; // UART RX, pin 0, disc-in TEST
    //p_pin14->IOCR0.B.PC1 = 0x10; // UART TX, pin 1, alt-func (see table 2.8, Infineon-TC38x-DataSheet-v01_02-EN.pdf) TEST
    //p_pin15->PDISC.U     = 0x00; // Digital function, not analog
    //p_pin15->IOCR0.B.PC2 = 0x00; // UART RX, pin 0, disc-in
    //p_pin15->IOCR0.B.PC3 = 0x12; // UART TX, pin 1, alt-func (see table 2.8, Infineon-TC38x-DataSheet-v01_02-EN.pdf)
    ///////////////////////////////////////////////////////////////////////////
    // Background Task
    ///////////////////////////////////////////////////////////////////////////
    while(1) {
        p_pin33->OUT.B.P4 = toggle;
        p_pin33->OUT.B.P5 = p_pin33->IN.B.P4;
        toggle            = 1 - toggle;
    }
}
